name: Build Test on Pull Request

on:
  pull_request:

permissions:
  contents: write
  id-token: write

concurrency:
  group: build_test
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        shell: bash
        run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Create release directory
        run: mkdir -p release

      - name: Cache release assets
        uses: actions/cache@v3
        with:
          path: ./release
          key: ${{ runner.os }}-release-${{github.sha}}
          restore-keys: |
            ${{ runner.os }}-release-

      - name: Build
        run: pnpm make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.GCLIENT }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ runner.os }}
          path: ./release
